### ISSUE TITLE
could  not create empty bitstream

### ISSUE THREAD

**Issue by ghyghy123** [epfl-vlsc/bitfiltrator#2]
hello ,I followed the steps but found that I couldn't generate a bitstream. Do you know how to solve it?
![image](https://user-images.githubusercontent.com/58417169/229500283-e70d825d-c08e-41bb-a658-6239cdd1e661.png)

**Comment by sahandKashani** [comment]
Hi,

It is not possible to say what the error is with your screenshot. The script should create some `_stderr` and `_stdout` files in the `database` directory based on your command. Can you share these files? They will point to the error.

```
.rw-r--r--   0 B  bit_stderr
.rw-r--r--  20 KB bit_stdout
.rw-r--r--   0 B  dcp_stderr
.rw-r--r--  42 KB dcp_stdout
.rw-r--r-- 266 KB empty.dcp
.rw-r--r--  15 MB empty_bitstream.bit
```

**Comment by ghyghy123** [comment]
hi,The screenshot is shown below. Can you explain what went wrong?
![image](https://user-images.githubusercontent.com/58417169/229526192-ed4d7c9d-4d72-450f-8d6f-0dce43dcd3c6.png)

**Comment by sahandKashani** [comment]
Hi,

You would need to share the contents of the `*_stderr` and `*_stdout` files. I unfortunately cannot tell what the error is from the names of the files alone.

**Comment by ghyghy123** [comment]
hi,The file is attached, thank you
[bit.zip](https://github.com/epfl-vlsc/bitfiltrator/files/11138927/bit.zip)

**Comment by sahandKashani** [comment]
Hi,

`bit_stdout`

```
 INFO: [Project 1-604] Checkpoint was created with Vivado v2017.2 (64-bit) build 1909853
  26   │ WARNING: [Vivado_Tcl 4-252] No drc_checks matched for command 'get_drc_checks PPURQ-1'
  27   │
  28   │     while executing
  29   │ "get_drc_checks {PPURQ-1}"
```

In the `src/tcl/gen_bitstream_from_dcp.tcl` file I had to disable the `PPURQ-1` DRC check to ensure a bitstream can be generated for HBM-enabled boards (e.g. some Alveo boards). It seems this DRC check does not exist in Vivado 2017.2 that you are using, but does in more recent versions of Vivado (I have tested bitfiltrator with only Vivado 2021.1 and 2022.1), so the command fails and Vivado exits.

It is likely you can simply comment out the line below to solve the issue (untested, but in theory should work).

https://github.com/epfl-vlsc/bitfiltrator/blob/main/src/tcl/gen_bitstream_from_dcp.tcl#L23-L33

**Comment by ghyghy123** [comment]
hi,The previous problem has been solved, but a new problem has arisen. Do you know how to solve it? The attachment is the generated file
[database.zip](https://github.com/epfl-vlsc/bitfiltrator/files/11139253/database.zip)


![image](https://user-images.githubusercontent.com/58417169/229537717-8fa2d6ef-575b-46ad-b0ab-bae212f70452.png)

**Comment by sahandKashani** [comment]
Hi,

It is the same error as before, but in another file (`src/tcl/one_ff_in_every_clb_column.tcl`). You have to comment out the `PPURQ-1` line again.

```
 457   │ WARNING: [Vivado_Tcl 4-252] No drc_checks matched for command 'get_drc_checks PPURQ-1'
 458   │
 459   │     while executing
 460   │ "get_drc_checks {PPURQ-1}"
 461   │     (procedure "main" line 57)
 462   │     invoked from within
 463   │ "main ${fpga_part} ${bitstream_out}"
 464   │     invoked from within
 465   │ "if { [llength $::argv] != 2 } {
 466   │   puts "received mandatory args: $::argv"
 467   │   puts "expected mandatory args: <fpga_part> <bitstream_out>"
 468   │ } else {
 469   │   set..."
 470   │     (file "/home/bitfiltrator-main/src/tcl/one_ff_in_every_clb_column.tcl" line 169)
 471   │ INFO: [Common 17-206] Exiting Vivado at Mon Apr  3 22:13:51 2023...
```

In general you should open up the `_stdout` or `_stderr` files to check what the errors say when a command fails. They will help pinpoint the issue and you will also learn more about Vivado's internals.

**Comment by ghyghy123** [comment]
Thank you very much. The problem has been resolved
