### ISSUE TITLE
Can we use this approach for other FPGAs?

### ISSUE THREAD

**Issue by akshar001** [epfl-vlsc/bitfiltrator#4]
We want to do this for efinix FPGAs, can we use this approach?

**Comment by sahandKashani** [comment]
Unfortunately not. Each family of FPGAs has a very different internal bitstream format. Bitfiltrator can be adapted for other Xilinx devices, but there is little chance that efinix FPGAs have a similar bitstream format.

You could probably use similar binary analysis techniques on efinix FPGAs, but you need to know something about what its bitstream contains. If efinix has a manual that partially describes the bitstream format, that would be your starting point. Otherwise, it will be very challenging.

**Comment by spzeno** [comment]
> Unfortunately not. Each family of FPGAs has a very different internal bitstream format. Bitfiltrator can be adapted for other Xilinx devices, but there is little chance that efinix FPGAs have a similar bitstream format.
> 
> You could probably use similar binary analysis techniques on efinix FPGAs, but you need to know something about what its bitstream contains. If efinix has a manual that partially describes the bitstream format, that would be your starting point. Otherwise, it will be very challenging.

Hi! Is it possible to use the same method for XIlinx 7 series FPGAs?

**Comment by sahandKashani** [comment]
Hi,

Yes, it is possible to use a very similar method for Xilinx 7 series FPGAs as the frame address structure in those devices is only slightly different than UltraScale/UltraScale+ devices. Check [UG470](https://docs.xilinx.com/v/u/en-US/ug470_7Series_Config), table 5-24 (pg 102).

![2024-03-09_21-19-30](https://github.com/epfl-vlsc/bitfiltrator/assets/2393156/d168878f-7776-454a-9b10-caa4e10f0b14)

The main difference with US/US+ devices is the existence of the top/bottom bit. The other fields in the FAR register (row/column/minor) differ in width compared to US/US+, but their meaning is the same.

Given the minor differences above, it should be fairly straightforward to parse the frame address using the 7-series addressing format and extract the same information that Bitfiltrator currently does for US/US+ devices.

**Comment by spzeno** [comment]
> Hi,
> 
> Yes, it is possible to use a very similar method for Xilinx 7 series FPGAs as the frame address structure in those devices is only slightly different than UltraScale/UltraScale+ devices. Check [UG470](https://docs.xilinx.com/v/u/en-US/ug470_7Series_Config), table 5-24 (pg 102).
> 
> ![2024-03-09_21-19-30](https://private-user-images.githubusercontent.com/2393156/311436951-d168878f-7776-454a-9b10-caa4e10f0b14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk5ODkxODQsIm5iZiI6MTcwOTk4ODg4NCwicGF0aCI6Ii8yMzkzMTU2LzMxMTQzNjk1MS1kMTY4ODc4Zi03Nzc2LTQ1NGEtOWIxMC1jYWE0ZTEwZjBiMTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDlUMTI1NDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRjYmRmMzYxNjM5N2M3M2M5ZTEwMjcwNzI2MTU3MDM0N2Y3YWNmMjI1MWEwY2IxNzA2YmNkMThkNmEyOTlmYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Rb64FYh457ZnLUgG2xRqaHerM-Mf4D7MabrCQfLTBo4)
> 
> The main difference with US/US+ devices is the existence of the top/bottom bit. The other fields in the FAR register (row/column/minor) differ in width compared to US/US+, but their meaning is the same.
> 
> Given the minor differences above, it should be fairly straightforward to parse the frame address using the 7-series addressing format and extract the same information that Bitfiltrator currently does for US/US+ devices.

Thanks very much!
